name       : libcloudproviders
version    : 0.3.2
release    : 8
source     :
    - https://download.gnome.org/sources/libcloudproviders/0.3/libcloudproviders-0.3.2.tar.xz : 24a9f3fffaf49f1d9d45d6ec35ba9f9e59a5a1040b51ce7835611131966c6819
license    : LGPL-3.0-or-later
component  : programming.library
summary    : libcloudproviders is a DBus API that allows cloud storage sync clients to expose their services.
description: |
    libcloudproviders is a DBus API that allows cloud storage sync clients to expose their services. Clients such as file managers and desktop environments can then provide integrated access to the cloud providers services.
builddeps  :
    - pkgconfig(glib-2.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
